#ifndef CYGONCE_PKGCONF_DEVS_USB_CORTEXM_STM32_H
#define CYGONCE_PKGCONF_DEVS_USB_CORTEXM_STM32_H
/*
 * File <pkgconf/devs_usb_cortexm_stm32.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_DEVS_USB_CORTEXM_STM32_TXEP_NUM 2
#define CYGNUM_DEVS_USB_CORTEXM_STM32_TXEP_NUM_2
#define CYGNUM_DEVS_USB_CORTEXM_STM32_RXEP_NUM 2
#define CYGNUM_DEVS_USB_CORTEXM_STM32_RXEP_NUM_2
#define CYGNUM_DEVS_USB_CORTEXM_STM32_EPO_MAX_MSG_SIZE 128
#define CYGNUM_DEVS_USB_CORTEXM_STM32_EPO_MAX_MSG_SIZE_128
#define CYGHWR_DEVS_USB_CORTEXM_STM32_DISC_PIN 30
#define CYGHWR_DEVS_USB_CORTEXM_STM32_DISC_PIN_30
#define CYGNUM_DEVS_USB_CORTEXM_STM32_ISR_PRIORITY 4
#define CYGNUM_DEVS_USB_CORTEXM_STM32_ISR_PRIORITY_4
#define CYGFUN_DEVS_USB_CORTEXM_STM32_PHY_CONFIG 1
#define CYGFUN_DEVS_USB_CORTEXM_STM32_PHY_TXEP1 1
#define CYGFUN_DEVS_USB_CORTEXM_STM32_PHY_TXEP2 1
#define CYGFUN_DEVS_USB_CORTEXM_STM32_PHY_RXEP3 1
#define CYGFUN_DEVS_USB_CORTEXM_STM32_PHY_RXEP4 1

#endif
