#ifndef CYGONCE_PKGCONF_SYSTEM_H
#define CYGONCE_PKGCONF_SYSTEM_H
/*
 * File <pkgconf/system.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_VERSION_CURRENT 0x7fffff00
#define CYGPKG_HAL_CORTEXM current
#define CYGPKG_HAL_CORTEXM_current
#define CYGNUM_HAL_CORTEXM_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_CORTEXM_VERSION_MINOR -1
#define CYGNUM_HAL_CORTEXM_VERSION_RELEASE -1
#define CYGBLD_HAL_ENDIAN_H <cyg/hal/cortexm_endian.h>
#define CYGPKG_HAL_CORTEXM_STM32 current
#define CYGPKG_HAL_CORTEXM_STM32_current
#define CYGNUM_HAL_CORTEXM_STM32_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_CORTEXM_STM32_VERSION_MINOR -1
#define CYGNUM_HAL_CORTEXM_STM32_VERSION_RELEASE -1
#define CYGPKG_HAL_CORTEXM_STM32_STM3210E_EVAL current
#define CYGPKG_HAL_CORTEXM_STM32_STM3210E_EVAL_current
#define CYGNUM_HAL_CORTEXM_STM32_STM3210E_EVAL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_CORTEXM_STM32_STM3210E_EVAL_VERSION_MINOR -1
#define CYGNUM_HAL_CORTEXM_STM32_STM3210E_EVAL_VERSION_RELEASE -1
#define CYGBLD_HAL_TARGET_H   <pkgconf/hal_cortexm.h>
#define CYGBLD_HAL_VARIANT_H  <pkgconf/hal_cortexm_stm32.h>
#define CYGBLD_HAL_PLATFORM_H <pkgconf/hal_cortexm_stm32_stm3210e_eval.h>
#define CYG_HAL_STARTUP RAM
#define CYG_HAL_STARTUP_RAM
#define CYGHWR_MEMORY_LAYOUT_LDI <pkgconf/mlt_cortexm_stm3210e_eval_ram.ldi>
#define CYGHWR_MEMORY_LAYOUT_H <pkgconf/mlt_cortexm_stm3210e_eval_ram.h>
#define CYGPKG_IO_SPI current
#define CYGPKG_IO_SPI_current
#define CYGNUM_IO_SPI_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_SPI_VERSION_MINOR -1
#define CYGNUM_IO_SPI_VERSION_RELEASE -1
#define CYGPKG_DEVS_SPI_CORTEXM_STM32 current
#define CYGPKG_DEVS_SPI_CORTEXM_STM32_current
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_VERSION_MINOR -1
#define CYGNUM_DEVS_SPI_CORTEXM_STM32_VERSION_RELEASE -1
#define CYGPKG_IO_USB current
#define CYGPKG_IO_USB_current
#define CYGNUM_IO_USB_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_USB_VERSION_MINOR -1
#define CYGNUM_IO_USB_VERSION_RELEASE -1
#define CYGPKG_DEVS_USB_CORTEXM_STM32 current
#define CYGPKG_DEVS_USB_CORTEXM_STM32_current
#define CYGNUM_DEVS_USB_CORTEXM_STM32_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_DEVS_USB_CORTEXM_STM32_VERSION_MINOR -1
#define CYGNUM_DEVS_USB_CORTEXM_STM32_VERSION_RELEASE -1
#define CYGPKG_HAL current
#define CYGPKG_HAL_current
#define CYGNUM_HAL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_HAL_VERSION_MINOR -1
#define CYGNUM_HAL_VERSION_RELEASE -1
#define CYGPKG_IO current
#define CYGPKG_IO_current
#define CYGNUM_IO_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_VERSION_MINOR -1
#define CYGNUM_IO_VERSION_RELEASE -1
#define CYGPKG_IO_SERIAL current
#define CYGPKG_IO_SERIAL_current
#define CYGNUM_IO_SERIAL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_IO_SERIAL_VERSION_MINOR -1
#define CYGNUM_IO_SERIAL_VERSION_RELEASE -1
#define CYGPKG_INFRA current
#define CYGPKG_INFRA_current
#define CYGNUM_INFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_INFRA_VERSION_MINOR -1
#define CYGNUM_INFRA_VERSION_RELEASE -1
#define CYGPKG_KERNEL current
#define CYGPKG_KERNEL_current
#define CYGNUM_KERNEL_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_KERNEL_VERSION_MINOR -1
#define CYGNUM_KERNEL_VERSION_RELEASE -1
#define CYGPKG_ERROR current
#define CYGPKG_ERROR_current
#define CYGNUM_ERROR_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ERROR_VERSION_MINOR -1
#define CYGNUM_ERROR_VERSION_RELEASE -1
#define CYGPKG_MEMALLOC current
#define CYGPKG_MEMALLOC_current
#define CYGNUM_MEMALLOC_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_MEMALLOC_VERSION_MINOR -1
#define CYGNUM_MEMALLOC_VERSION_RELEASE -1
#define CYGPKG_LIBC_STRING current
#define CYGPKG_LIBC_STRING_current
#define CYGNUM_LIBC_STRING_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_LIBC_STRING_VERSION_MINOR -1
#define CYGNUM_LIBC_STRING_VERSION_RELEASE -1
#define CYGPKG_ISOINFRA current
#define CYGPKG_ISOINFRA_current
#define CYGNUM_ISOINFRA_VERSION_MAJOR CYGNUM_VERSION_CURRENT
#define CYGNUM_ISOINFRA_VERSION_MINOR -1
#define CYGNUM_ISOINFRA_VERSION_RELEASE -1

#endif
