#ifndef CYGONCE_PKGCONF_HAL_SH_SH7750_DREAMCAST_H
#define CYGONCE_PKGCONF_HAL_SH_SH7750_DREAMCAST_H
/*
 * File <pkgconf/hal_sh_sh7750_dreamcast.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_HAL_SH_SH4_SCIF_PORTS 1
#define CYGHWR_HAL_VSR_TABLE 0x8c010000
#define CYGHWR_HAL_VECTOR_TABLE 0x8c010100
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_1
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_0
#define CYGNUM_HAL_SH_SH4_SCIF_BAUD_RATE_DEFAULT 115200
#define CYGNUM_HAL_SH_SH4_SCIF_BAUD_RATE_DEFAULT_115200
#define CYGHWR_HAL_SH_OOC_CKIO 1
#define CYGHWR_HAL_SH_OOC_PLL_1 6
#define CYGHWR_HAL_SH_OOC_PLL_1_6
#define CYGHWR_HAL_SH_OOC_PLL_2 1
#define CYGHWR_HAL_SH_OOC_PLL_2_1
#define CYGHWR_HAL_SH_OOC_DIVIDER_IFC 1
#define CYGHWR_HAL_SH_OOC_DIVIDER_IFC_1
#define CYGHWR_HAL_SH_OOC_DIVIDER_BFC 2
#define CYGHWR_HAL_SH_OOC_DIVIDER_BFC_2
#define CYGHWR_HAL_SH_OOC_DIVIDER_PFC 4
#define CYGHWR_HAL_SH_OOC_DIVIDER_PFC_4
#define CYGHWR_HAL_SH_OOC_CLOCK_MODE 5
#define CYGHWR_HAL_SH_OOC_CLOCK_MODE_5
#define CYGBLD_GLOBAL_OPTIONS 1

#endif
