#ifndef CYGONCE_PKGCONF_HAL_POWERPC_EC555_H
#define CYGONCE_PKGCONF_HAL_POWERPC_EC555_H
/*
 * File <pkgconf/hal_powerpc_ec555.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGHWR_HAL_EC555_BOARD_VARIANT F02_S01
#define CYGHWR_HAL_EC555_BOARD_VARIANT_F02_S01
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 2
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_2
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_1
#define CYGHWR_HAL_POWERPC_BOARD_SPEED 40
#define CYGHWR_HAL_POWERPC_BOARD_SPEED_40
#define CYGHWR_HAL_POWERPC_FORCE_VECTOR_BASE_LOW 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 38400
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_38400
#define CYGNUM_HAL_RTC_CONSTANTS 1
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 100
#define CYGNUM_HAL_RTC_DENOMINATOR_100
#define CYGNUM_HAL_RTC_PERIOD 25000
#define CYGNUM_HAL_RTC_PERIOD_25000
#define CYGBLD_GLOBAL_OPTIONS 1

#endif
