#ifndef CYGONCE_PKGCONF_HAL_SH_SH4_H
#define CYGONCE_PKGCONF_HAL_SH_SH4_H
/*
 * File <pkgconf/hal_sh_sh4.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGBLD_HAL_VAR_EXCEPTION_MODEL_H   <cyg/hal/hal_var_bank.h>
#define CYGBLD_HAL_VAR_EXCEPTION_MODEL_INC <cyg/hal/hal_var_bank.inc>
#define CYGBLD_HAL_VAR_INTR_MODEL_H   <cyg/hal/hal_intr_excevt.h>
#define CYGINT_HAL_SH_CPG_T1 1
#define CYGINT_HAL_SH_CPG_T1_1
#define CYGHWR_HAL_SH_TMU_PRESCALE_0 4
#define CYGHWR_HAL_SH_TMU_PRESCALE_0_4
#define CYGHWR_HAL_SH_RTC_PRESCALE 4
#define CYGHWR_HAL_SH_RTC_PRESCALE_4
#define CYGHWR_HAL_SH_PROCESSOR_SPEED 199999998
#define CYGHWR_HAL_SH_PROCESSOR_SPEED_199999998
#define CYGHWR_HAL_SH_BOARD_SPEED 99999999
#define CYGHWR_HAL_SH_BOARD_SPEED_99999999
#define CYGHWR_HAL_SH_ONCHIP_PERIPHERAL_SPEED 49999999
#define CYGHWR_HAL_SH_ONCHIP_PERIPHERAL_SPEED_49999999
#define CYGNUM_HAL_SH_SH4_SCIF_BAUD_RATE 115200
#define CYGNUM_HAL_SH_SH4_SCIF_BAUD_RATE_115200
#define CYGHWR_HAL_SH_CACHE_MODE_P0 WRITE_BACK
#define CYGHWR_HAL_SH_CACHE_MODE_P0_WRITE_BACK
#define CYGHWR_HAL_SH_CACHE_MODE_P1 WRITE_BACK
#define CYGHWR_HAL_SH_CACHE_MODE_P1_WRITE_BACK

#endif
