#ifndef CYGONCE_PKGCONF_HAL_ARM_ARM9_EXCALIBUR_H
#define CYGONCE_PKGCONF_HAL_ARM_ARM9_EXCALIBUR_H
/*
 * File <pkgconf/hal_arm_arm9_excalibur.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define HAL_PLATFORM_CPU    "ARM9"
#define HAL_PLATFORM_BOARD  "EXCALIBUR system"
#define HAL_PLATFORM_EXTRA  ""
#define HAL_ARCH_PROGRAM_NEW_STACK excalibur_program_new_stack
#define HAL_PLATFORM_MACHINE_TYPE  62
#define CYGNUM_HAL_ARM_EXCALIBUR_CPU_CLOCK 150000000
#define CYGNUM_HAL_ARM_EXCALIBUR_CPU_CLOCK_150000000
#define CYGNUM_HAL_ARM_EXCALIBUR_PERIPHERAL_CLOCK 75000000
#define CYGNUM_HAL_ARM_EXCALIBUR_PERIPHERAL_CLOCK_75000000
#define CYGNUM_HAL_ARM_EXCALIBUR_SDRAM_CLOCK 75000000
#define CYGNUM_HAL_ARM_EXCALIBUR_SDRAM_CLOCK_75000000
#define CYGNUM_HAL_ARM_EXCALIBUR_TIMER_PRESCALE 16
#define CYGNUM_HAL_ARM_EXCALIBUR_TIMER_PRESCALE_16
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 100
#define CYGNUM_HAL_RTC_DENOMINATOR_100
#define CYGNUM_HAL_RTC_PERIOD 46874
#define CYGNUM_HAL_RTC_PERIOD_46874
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 57600
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_57600
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD 57600
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD_57600
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_1
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT_0
#define CYGSEM_HAL_USE_ROM_MONITOR GDB_stubs
#define CYGSEM_HAL_USE_ROM_MONITOR_GDB_stubs

#endif
