#ifndef CYGONCE_PKGCONF_HAL_FRV_FRV400_H
#define CYGONCE_PKGCONF_HAL_FRV_FRV400_H
/*
 * File <pkgconf/hal_frv_frv400.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define HAL_PLATFORM_CPU    "Fujitsu FR400"
#define HAL_PLATFORM_BOARD  "MB93091-CB10 evaluation board"
#define HAL_PLATFORM_EXTRA  ""
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 2
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_2
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_DEFAULT_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 38400
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_38400
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD 38400
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD_38400
#define CYGSEM_HAL_DIAG_USES_LEDS 1
#define CYGNUM_HAL_RTC_CONSTANTS 1
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 100
#define CYGNUM_HAL_RTC_DENOMINATOR_100
#define CYGNUM_HAL_RTC_PERIOD 10000
#define CYGNUM_HAL_RTC_PERIOD_10000
#define CYGBLD_GLOBAL_OPTIONS 1
#define CYGSEM_HAL_USE_ROM_MONITOR GDB_stubs
#define CYGSEM_HAL_USE_ROM_MONITOR_GDB_stubs

#endif
