src/arm9_misc.o.d: \
 /home/grihey/LAB/ecos/packages/hal/arm/arm9/var/current/src/arm9_misc.c \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/pkgconf/hal.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/pkgconf/system.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/pkgconf/hal_arm.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/pkgconf/hal_arm_arm9.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/pkgconf/hal_arm_arm9_excalibur.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/cyg/infra/cyg_type.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/stddef.h \
 /home/grihey/src/ecos/gnutools/arm-eabi/bin/../lib/gcc/arm-eabi/4.6.3/include/stddef.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/cyg/hal/basetype.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/cyg/hal/hal_if.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/cyg/hal/dbg-threads-api.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/cyg/hal/dbg-thread-syscall.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/stdarg.h \
 /home/grihey/src/ecos/gnutools/arm-eabi/bin/../lib/gcc/arm-eabi/4.6.3/include/stdarg.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/cyg/hal/hal_arch.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/cyg/hal/hal_io.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/cyg/hal/var_io.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/cyg/hal/plf_io.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/cyg/hal/excalibur.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/cyg/hal/hal_cache.h \
 /home/grihey/src/ecos/ecos-3.0/Configs/untitled_install/include/cyg/hal/hal_mmu.h
